export const ActionTypes = {
  FETCH_NOTES: "FETCH_NOTES",
  FETCH_SEARCH_NOTES: "FETCH_SEARCH_NOTES",
  POST_NEW_NOTE: "POST_NEW_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  ADD_TO_TRASH: "ADD_TO_TRASH",
  DELETE_FROM_TRASH: "DELETE_FROM_TRASH",
  DELETE_NOTE: "DELETE_NOTE",
  DELETE:"DELETE",
  VIEW:"VIEW"
};
